### ISSUE TITLE
Xhost + failed

### ISSUE THREAD

**Issue by asd2333** [leimao/Docker-WeChat#1]
I have download images 
![2022-03-28 10-47-45 的屏幕截图](https://user-images.githubusercontent.com/20329012/160318105-604d8f63-88fe-41e4-a798-6fca8340bb80.png)
but exec command " xhost + " failed
I try root and myself account ,always failed 
![2022-03-28 10-51-04 的屏幕截图](https://user-images.githubusercontent.com/20329012/160318343-b5c453f3-a056-407a-b0e9-1d40d2e1df3b.png)
how to do do

**Comment by leimao** [comment]
This is not an error message. Please proceed with `docker run`.

**Comment by asd2333** [comment]
thanks, weixin has running
